apiVersion: v2
description: Airflow Helm Chart (Forked of course from the User Community) - used to deploy Apache Airflow on Kubernetes
name: airflow
version: 8.6.1
appVersion: 2.2.5
icon: https://airflow.apache.org/_images/pin_large.png
home: https://github.com/cristiancalugaru/airflow-helm-charts
maintainers:
  - name: cristiancalugaru
    url: https://github.com/cristiancalugaru
sources:
  - https://github.com/cristiancalugaru/airflow-helm-charts/tree/disable_pv_checks/charts/airflow
keywords:
  - airflow
  - dag
  - workflow
dependencies:
  - name: postgresql
    version: 8.6.4
    repository: https://charts.helm.sh/stable
    condition: postgresql.enabled
  - name: redis
    version: 10.5.7
    repository: https://charts.helm.sh/stable
    condition: redis.enabled
